image: docker:latest

services:
  - name: docker:dind
    command: ["--experimental"]

stages:
- build

build:
  stage: build
  script:
    - docker build --squash --compress --pull --tag local/evdev:latest .
    - docker save -o evdev.tar local/evdev
    - ls -l
    - docker run --rm --volume "$PWD":/workdir local/evdev sudo 7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on evdev.z evdev.tar
    - du -sh evdev.z
  artifacts:
    paths:
    - evdev.z
