language: generic
sudo: required
services:
- docker
jobs:
  include:
    - stage: Prepare EvDev Build
      script:
      - docker version
      - 'echo "{ \"experimental\": true, \"storage-driver\": \"overlay2\", \"max-concurrent-downloads\": 50, \"max-concurrent-uploads\": 50 }" | sudo tee /etc/docker/daemon.json'
      - sudo service docker restart
    - stage: Build EvDev Base
      script:
      - docker build -f Dockerfile.base --compress --pull --tag ler0ever/evdev.base .
      after_success:
      - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push "ler0ever/evdev.base"'
    - stage: Build EvDev Language Support
      script:
      - docker build -f Dockerfile.lang --compress --pull --tag ler0ever/evdev.lang .
      after_success:
      - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push "ler0ever/evdev.lang"'
    - stage: Build EvDev Editors and Utilities
      script:
      - docker build -f Dockerfile.utils --compress --pull --tag ler0ever/evdev.utils .
      after_success:
      - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push "ler0ever/evdev.utils"'
    - stage: Build EvDev EverVim
      script:
      - docker build -f Dockerfile.evervim --compress --pull --tag ler0ever/evdev.evervim .
      after_success:
      - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push "ler0ever/evdev.evervim"'
    - stage: Build EvDev Spacemacs
      script:
      - docker build -f Dockerfile.spacemacs --compress --pull --tag ler0ever/evdev.spacemacs .
      after_success:
      - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push "ler0ever/evdev.spacemacs"'
    - stage: Build EvDev User Configuration
      script:
      - docker build -f Dockerfile.config --compress --pull --tag ler0ever/evdev.config .
      after_success:
      - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push "ler0ever/evdev.config"'
    - stage: Build EvDev Docker Image
      script:
      - docker build --compress --pull --tag ler0ever/evdev .
      after_success:
      - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push "ler0ever/evdev"'
